### ISSUE TITLE
Windows 10 64 Bit User reported broken library

### ISSUE THREAD

**Issue by jnslxndr** [muthesius/WebSocketP5#6]
… to be investigated on a windows machine

**Comment by dackdel** [comment]
is this still a problem. I have it working on my win 10 64.

**Comment by jnslxndr** [comment]
@dackdel I don't know. I filed the issue myself, because I had a user report it. The reporting person never got back to me though. Thanks for reporting it working 😃 I will close this and re-open if it occurs again.
